/**
 * PASSIVE VENDOR FINGERPRINTS — who is in front of this site, block or no block.
 *
 * `detectChallenge` answers "what is blocking me right now". This answers the wider
 * question: "whose stack is this response passing through" — including on clean 200s,
 * where no challenge fires but the vendor still rides the response (cf-ray on every
 * Cloudflare page, _abck on every Akamai Bot Manager page, etc).
 *
 * Signatures are data, not code: each entry lists header names, header value patterns,
 * cookie names, and body markers. A vendor is reported with every piece of evidence found.
 */

import { headerVal, type DetectInput } from './detect.js';

export type VendorKind = 'waf' | 'cdn' | 'captcha' | 'bot-manager';

export interface VendorSignature {
  name: string;
  kind: VendorKind;
  /** exact header names whose presence is evidence */
  headers?: string[];
  /** [headerName, valuePattern] pairs */
  headerValues?: [string, RegExp][];
  /** cookie names (matched inside set-cookie) */
  cookies?: string[];
  /** body markers */
  bodyPatterns?: RegExp[];
  /** one-line "what this means for a scraper" */
  note: string;
}

export interface VendorHit {
  name: string;
  kind: VendorKind;
  evidence: string[];
  note: string;
}

export const SIGNATURES: VendorSignature[] = [
  {
    name: 'cloudflare',
    kind: 'waf',
    headers: ['cf-ray', 'cf-mitigated', 'cf-cache-status', 'cf-request-id'],
    headerValues: [['server', /^cloudflare$/i]],
    cookies: ['__cf_bm', 'cf_clearance'],
    bodyPatterns: [/challenge-platform/i, /__cf_chl_/i, /challenges\.cloudflare\.com/i],
    note: 'JS challenge + managed challenge + Turnstile. Transport (TLS/JA3) and session layers both scored.',
  },
  {
    name: 'datadome',
    kind: 'bot-manager',
    headers: ['x-datadome', 'x-dd-debug'],
    cookies: ['datadome'],
    bodyPatterns: [/api-js\.datadome\.co/i, /geo\.captcha-delivery\.com/i, /dd_cookie_test_/i],
    note: 'Behavioral scoring + device fingerprint. Session continuity matters more than raw volume.',
  },
  {
    name: 'perimeterx',
    kind: 'bot-manager',
    headers: ['x-px-original-token'],
    cookies: ['_pxhd', '_pxff_ts'],
    bodyPatterns: [/perimeterx/i, /px-captcha/i, /_px[A-Z0-9]/i, /px-client/i],
    note: 'Now HUMAN. Sensor JS + behavioral model. Mobile SDK common on app APIs.',
  },
  {
    name: 'akamai',
    kind: 'bot-manager',
    headerValues: [['server', /AkamaiGHost|Akamai/i]],
    headers: ['x-akamai-transformed'],
    cookies: ['_abck', 'ak_bmsc', 'bm_sv', 'akaalb'],
    bodyPatterns: [/Reference\s*#\s*[0-9a-f.]+/i, /akam\.net/i],
    note: 'Bot Manager sensor (_abck) + edge deny. TLS fingerprint scored at the edge.',
  },
  {
    name: 'kasada',
    kind: 'bot-manager',
    headers: ['x-kpsdk-ct', 'x-kpsdk-v', 'x-kpsdk-h'],
    bodyPatterns: [/kpsdk/i, /\/ips\.js/i],
    note: 'Proof-of-work style client puzzle (ips.js). Hardest of the majors to fake passively.',
  },
  {
    name: 'imperva',
    kind: 'waf',
    headers: ['x-iinfo', 'x-cdn-forward'],
    cookies: ['incap_ses_', 'visid_incap_', 'nlbi_'],
    bodyPatterns: [/incapsula incident id/i, /_incapsula_ resource/i],
    note: 'Incapsula. Cookie-based session gating with occasional JS challenges.',
  },
  {
    name: 'awswaf',
    kind: 'waf',
    headers: ['x-amzn-waf-action', 'x-amzn-waf-rulegroup'],
    cookies: ['aws-waf-token'],
    note: 'AWS WAF challenge/CAPTCHA action. Token cookie carries the clearance.',
  },
  {
    name: 'distil',
    kind: 'bot-manager',
    headers: ['x-distil-cs'],
    bodyPatterns: [/distil_r_captcha/i, /Pardon Our Interruption/i],
    note: 'Distil Networks, now Imperva Advanced Bot Protection. JS sensor + device fingerprint.',
  },
  {
    name: 'queueit',
    kind: 'bot-manager',
    cookies: ['queueitaccepted'],
    bodyPatterns: [/queue-it\.net/i],
    note: 'Queue-it virtual waiting room. Not a ban — a softgate; the QueueITAccepted cookie is the token.',
  },
  {
    name: 'sucuri',
    kind: 'waf',
    headers: ['x-sucuri-id', 'x-sucuri-cache'],
    bodyPatterns: [/Sucuri Website Firewall/i, /sucuri\.net/i],
    note: 'Cloud proxy WAF. Blocks are usually IP/ASN reputation — fix egress, not JS.',
  },
  {
    name: 'wordfence',
    kind: 'waf',
    cookies: ['wfwaf-authcookie'],
    bodyPatterns: [/generated by wordfence/i, /wordfence/i],
    note: 'WordPress plugin WAF. 503s are rate limiting; tune cadence, not fingerprints.',
  },
  {
    name: 'f5bigip',
    kind: 'waf',
    headers: ['x-wa-info'],
    cookies: ['bigipserver', 'f5_cspm'],
    bodyPatterns: [/The requested URL was rejected\. Please consult with your administrator/i],
    note: 'F5 BIG-IP ASM. The rejection page carries a support ID — a rule fired on the request itself.',
  },
  {
    name: 'azure',
    kind: 'waf',
    headers: ['x-azure-ref'],
    headerValues: [['server', /Microsoft-Azure-Application-Gateway|Azure Front Door/i]],
    bodyPatterns: [/The request is blocked\./i],
    note: 'Azure Front Door / Application Gateway WAF. Block page carries a tracking reference (x-azure-ref).',
  },
  {
    name: 'cloudarmor',
    kind: 'waf',
    headerValues: [['server', /^(Google Frontend|ESF)$/i]],
    bodyPatterns: [/your client does not have permission to get URL/i],
    note: 'Google front end — Cloud Armor may be attached. Armor blocks are bare 403s with Google branding.',
  },
  {
    name: 'ddosguard',
    kind: 'waf',
    headerValues: [['server', /ddos-guard/i]],
    cookies: ['__ddg'],
    bodyPatterns: [/DDoS-Guard/i],
    note: 'DDoS-Guard. JS check similar to Cloudflare UAM; __ddg* cookies carry the clearance.',
  },
  {
    name: 'signalsciences',
    kind: 'waf',
    headers: ['x-sigsci-requestid', 'x-sigsci-agentresponse'],
    note: 'Fastly Next-Gen WAF (Signal Sciences). Rule-based; blocks carry the request id for support.',
  },
  {
    name: 'reblaze',
    kind: 'bot-manager',
    headerValues: [['server', /Reblaze/i]],
    cookies: ['rbzid', 'rbzsessionid'],
    bodyPatterns: [/Reblaze/i],
    note: 'Reblaze bot mitigation. Session-scoped JS challenge; rbzid cookie is the session token.',
  },
  {
    name: 'radware',
    kind: 'bot-manager',
    cookies: ['reese84'],
    bodyPatterns: [/reese84/i],
    note: 'Radware Bot Manager (ex-ShieldSquare). reese84 sensor cookie + behavioral scoring.',
  },
  {
    name: 'modsecurity',
    kind: 'waf',
    headerValues: [['server', /mod_security|Mod_Security/i]],
    bodyPatterns: [/mod_security|modsecurity/i],
    note: 'ModSecurity / OWASP CRS. Signature rules on the request itself — 406/403 means a rule matched your payload or headers.',
  },
  {
    name: 'safeline',
    kind: 'waf',
    bodyPatterns: [/SafeLine/i],
    note: 'SafeLine (open-source WAF by Chaitin). Self-hosted, semantic analysis, growing on Chinese sites.',
  },
  {
    name: 'fastly',
    kind: 'cdn',
    headers: ['x-served-by', 'x-cache-hits', 'fastly-restarts'],
    headerValues: [['server', /^Varnish$/i]],
    note: 'CDN layer. WAF (Signal Sciences/Next-Gen) may or may not be enabled behind it.',
  },
  {
    name: 'cloudfront',
    kind: 'cdn',
    headers: ['x-amz-cf-id', 'x-amz-cf-pop'],
    headerValues: [['via', /CloudFront/i]],
    note: 'AWS CDN. Often paired with AWS WAF or a custom Lambda@Edge gate.',
  },
  {
    name: 'vercel',
    kind: 'cdn',
    headers: ['x-vercel-id', 'x-vercel-cache'],
    headerValues: [['server', /^Vercel$/i]],
    note: 'Vercel edge. Built-in bot protection is opt-in; check for challenge behavior.',
  },
  {
    name: 'bunnycdn',
    kind: 'cdn',
    headerValues: [['server', /BunnyCDN/i]],
    headers: ['cdn-pullzone', 'cdn-requestcountrycode'],
    note: 'BunnyCDN edge. Optional edge rules; often no bot management at all.',
  },
  {
    name: 'netlify',
    kind: 'cdn',
    headerValues: [['server', /^Netlify$/i]],
    headers: ['x-nf-request-id'],
    note: 'Netlify edge. No built-in bot manager — blocks are usually custom edge functions.',
  },
  {
    name: 'alibaba',
    kind: 'cdn',
    headers: ['eagleid'],
    headerValues: [['server', /Tengine/i]],
    note: 'Alibaba Cloud edge (Tengine). Aliyun WAF may sit behind it; common on Chinese e-commerce.',
  },
  {
    name: 'recaptcha',
    kind: 'captcha',
    bodyPatterns: [/g-recaptcha/i, /recaptcha\/api\.js/i, /grecaptcha\.execute/i],
    note: 'Google reCAPTCHA v2/v3 or Enterprise. v3 scores silently; v2 challenges visibly.',
  },
  {
    name: 'hcaptcha',
    kind: 'captcha',
    bodyPatterns: [/h-captcha/i, /hcaptcha\.com/i],
    note: 'hCaptcha widget or Enterprise risk score.',
  },
  {
    name: 'turnstile',
    kind: 'captcha',
    bodyPatterns: [/challenges\.cloudflare\.com\/turnstile/i, /cf-turnstile/i],
    note: 'Cloudflare Turnstile — managed, mostly non-interactive, still a scored signal.',
  },
  {
    name: 'funcaptcha',
    kind: 'captcha',
    bodyPatterns: [/funcaptcha/i, /arkoselabs/i],
    note: 'Arkose Labs. Interactive challenges, expensive to solve at scale.',
  },
  {
    name: 'geetest',
    kind: 'captcha',
    bodyPatterns: [/api\.geetest\.com/i, /initGeetest/i, /geetest/i],
    note: 'GeeTest CAPTCHA (v3/v4). Slider/puzzle challenges; common on Chinese and gaming sites.',
  },
];

function cookieBlob(headers: DetectInput['headers']): string {
  const raw = headerVal(headers, 'set-cookie') ?? '';
  return raw.toLowerCase();
}

export function fingerprintVendors(input: Pick<DetectInput, 'headers' | 'body'>): VendorHit[] {
  const { headers, body } = input;
  const cookies = cookieBlob(headers);
  const hits: VendorHit[] = [];

  for (const sig of SIGNATURES) {
    const evidence: string[] = [];

    for (const h of sig.headers ?? []) {
      if (headerVal(headers, h) !== null) evidence.push(`header: ${h}`);
    }
    for (const [h, re] of sig.headerValues ?? []) {
      const v = headerVal(headers, h);
      if (v !== null && re.test(v)) evidence.push(`header: ${h}: ${v}`);
    }
    for (const c of sig.cookies ?? []) {
      if (cookies.includes(c.toLowerCase())) evidence.push(`cookie: ${c}`);
    }
    for (const re of sig.bodyPatterns ?? []) {
      const m = body.match(re);
      if (m) evidence.push(`body: "${m[0]}"`);
    }

    if (evidence.length > 0) {
      hits.push({ name: sig.name, kind: sig.kind, evidence, note: sig.note });
    }
  }
  return hits;
}
